"""add aktif field to TahunAjaran

Revision ID: 106b6442b206
Revises: 5f423ecbe048
Create Date: 2025-09-07 22:10:28.806696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106b6442b206'
down_revision = '5f423ecbe048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tahun_ajaran', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aktif', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tahun_ajaran', schema=None) as batch_op:
        batch_op.drop_column('aktif')

    # ### end Alembic commands ###
