"""perubahan tabel pegawai dan sekolah

Revision ID: 5f423ecbe048
Revises: e8beb216caa5
Create Date: 2025-09-06 21:08:32.091402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f423ecbe048'
down_revision = 'e8beb216caa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kelas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sekolah_id', sa.Integer(), nullable=False))
        batch_op.alter_column('tahun_ajaran_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.create_foreign_key(None, 'sekolah', ['sekolah_id'], ['id'])

    with op.batch_alter_table('pegawai', schema=None) as batch_op:
        batch_op.drop_column('jabatan')

    with op.batch_alter_table('siswa', schema=None) as batch_op:
        batch_op.alter_column('jenis_kelamin',
               existing_type=mysql.VARCHAR(length=1),
               type_=sa.Enum('L', 'P', name='jenis_kelamin_enum'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siswa', schema=None) as batch_op:
        batch_op.alter_column('jenis_kelamin',
               existing_type=sa.Enum('L', 'P', name='jenis_kelamin_enum'),
               type_=mysql.VARCHAR(length=1),
               nullable=True)

    with op.batch_alter_table('pegawai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jabatan', mysql.VARCHAR(length=50), nullable=True))

    with op.batch_alter_table('kelas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('tahun_ajaran_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('sekolah_id')

    # ### end Alembic commands ###
