"""add tingkat column to kelas

Revision ID: c9d3dd1e9125
Revises: f9021d10525f
Create Date: 2026-05-20 10:47:08.584505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d3dd1e9125'
down_revision = 'f9021d10525f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kelas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tingkat', sa.Integer(), nullable=True))

    with op.batch_alter_table('siswa', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_nisn_per_kelas', ['nisn', 'kelas_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siswa', schema=None) as batch_op:
        batch_op.drop_constraint('uq_nisn_per_kelas', type_='unique')

    with op.batch_alter_table('kelas', schema=None) as batch_op:
        batch_op.drop_column('tingkat')

    # ### end Alembic commands ###
