"""initial

Revision ID: d68b7f5b5249
Revises: 
Create Date: 2025-09-06 12:21:49.454710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68b7f5b5249'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('log_aktivitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('aksi', sa.String(length=50), nullable=True),
    sa.Column('tabel', sa.String(length=50), nullable=True),
    sa.Column('entri_id', sa.Integer(), nullable=True),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provinsi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kabupaten',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provinsi_id', sa.Integer(), nullable=True),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['provinsi_id'], ['provinsi.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kecamatan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kabupaten_id', sa.Integer(), nullable=True),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kabupaten_id'], ['kabupaten.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sekolah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kecamatan_id', sa.Integer(), nullable=True),
    sa.Column('nama_sekolah', sa.String(length=100), nullable=False),
    sa.Column('npsn', sa.String(length=50), nullable=True),
    sa.Column('jenjang', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kecamatan_id'], ['kecamatan.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('npsn')
    )
    op.create_table('pegawai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sekolah_id', sa.Integer(), nullable=True),
    sa.Column('nip', sa.String(length=50), nullable=True),
    sa.Column('jabatan', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sekolah_id'], ['sekolah.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nip')
    )
    op.create_table('tahun_ajaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sekolah_id', sa.Integer(), nullable=True),
    sa.Column('tahun_ajaran', sa.String(length=20), nullable=False),
    sa.Column('semester', sa.String(length=20), nullable=False),
    sa.Column('kepala_sekolah_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kepala_sekolah_id'], ['pegawai.id'], ),
    sa.ForeignKeyConstraint(['sekolah_id'], ['sekolah.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tahun_ajaran_id', sa.Integer(), nullable=True),
    sa.Column('nama_kelas', sa.String(length=50), nullable=True),
    sa.Column('wali_kelas_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tahun_ajaran_id'], ['tahun_ajaran.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wali_kelas_id'], ['pegawai.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kelas_id', sa.Integer(), nullable=True),
    sa.Column('nama_siswa', sa.String(length=100), nullable=True),
    sa.Column('jenis_kelamin', sa.String(length=1), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kebiasaan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siswa_id', sa.Integer(), nullable=True),
    sa.Column('kelas_id', sa.Integer(), nullable=True),
    sa.Column('bulan', sa.String(length=7), nullable=False),
    sa.Column('bangun_pagi', sa.Integer(), nullable=True),
    sa.Column('beribadah', sa.Integer(), nullable=True),
    sa.Column('berolahraga', sa.Integer(), nullable=True),
    sa.Column('sehat_dan_lemar', sa.Integer(), nullable=True),
    sa.Column('belajar', sa.Integer(), nullable=True),
    sa.Column('bermasyarakat', sa.Integer(), nullable=True),
    sa.Column('tidur_cepat', sa.Integer(), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.ForeignKeyConstraint(['siswa_id'], ['siswa.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kebiasaan')
    op.drop_table('siswa')
    op.drop_table('kelas')
    op.drop_table('tahun_ajaran')
    op.drop_table('pegawai')
    op.drop_table('sekolah')
    op.drop_table('kecamatan')
    op.drop_table('kabupaten')
    op.drop_table('provinsi')
    op.drop_table('log_aktivitas')
    op.drop_table('users')
    # ### end Alembic commands ###
