"""remove log from master tables

Revision ID: e8beb216caa5
Revises: d68b7f5b5249
Create Date: 2025-09-06 12:46:13.322915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8beb216caa5'
down_revision = 'd68b7f5b5249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kabupaten', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('kabupaten_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('kabupaten_ibfk_3'), type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('updated_by')

    with op.batch_alter_table('kecamatan', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('kecamatan_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('kecamatan_ibfk_3'), type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('updated_by')

    with op.batch_alter_table('provinsi', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('provinsi_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('provinsi_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('updated_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provinsi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('provinsi_ibfk_1'), 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('provinsi_ibfk_2'), 'users', ['updated_by'], ['id'])

    with op.batch_alter_table('kecamatan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('kecamatan_ibfk_3'), 'users', ['updated_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('kecamatan_ibfk_1'), 'users', ['created_by'], ['id'])

    with op.batch_alter_table('kabupaten', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('kabupaten_ibfk_3'), 'users', ['updated_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('kabupaten_ibfk_1'), 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###
