"""add nisn column to siswa

Revision ID: ecc2815db3da
Revises: 106b6442b206
Create Date: 2025-10-08 21:52:48.242343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ecc2815db3da'
down_revision = '106b6442b206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siswa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nisn', sa.String(length=20), nullable=True))
        batch_op.alter_column('nama_siswa',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['nisn'])
        batch_op.drop_constraint('siswa_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('siswa_ibfk_1', type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('updated_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siswa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.create_foreign_key('siswa_ibfk_1', 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key('siswa_ibfk_3', 'users', ['updated_by'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('nama_siswa',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('nisn')

    # ### end Alembic commands ###
